# eureka-server

server:
  port: ${port:8761} # from env variable

eureka:
  instance:
    hostname: ${hostname:localhost} # from env variable
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
